# tekartik analysis_options extension to pedantic
include: package:tekartik_common_utils/pedantic/analysis_options.strong_mode.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude: [build/**]
  #   exclude:
  #     - path/to/excluded/files/**
  errors:
    uri_has_not_been_generated: ignore

