name: tekartik_angular_utils
description: A Dart app that uses Angular
version: 0.2.3+1
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  angular: '>=5.0.0'
  angular_components: '>=0.9.0'
  tekartik_test_menu_browser:
    git:
      url: git://github.com/tekartik/test_menu.dart
      path: test_menu_browser
      ref: dart2
    version: '>=0.4.6'
  tekartik_app_utils:
    git:
      url: git://github.com/tekartik/app_utils.dart
      ref: dart2
    version: '>=0.4.0'
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.6.5'

dev_dependencies:
  process_run: '>=0.10.1'
  dev_test: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  angular_test: '>=2.0.0'
  build_runner: '>=0.10.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  test: '>=1.0.0'
# dependency_overrides:
#  tekartik_app_utils:
#    path: ../tekartik_app_utils.dart
#  tekartik_build_utils:
#    path: ../build_utils.dart