name: tekartik_angular_utils
description: A Dart app that uses Angular
version: 0.1.0
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular: '>=4.0.0-beta'
  angular_components: '>=0.5.0'
  tekartik_app_utils:
    git: git://github.com/tekartik/app_utils.dart
  tekartik_build_utils:
    git: git://github.com/tekartik/build_utils.dart

dev_dependencies:
  browser: '>=0.10.0'
  test: any
  dev_test: any
  dart_to_js_script_rewriter: '>=1.0.1'
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
transformers:
- angular:
    entry_points:
    - web/main.dart
    - example/side_bar/main.dart
    - example/layout/page_layout/main.dart
    - example/view/wait_box/main.dart
- dart_to_js_script_rewriter
dependency_overrides:
#  tekartik_app_utils:
#    path: ../tekartik_app_utils.dart
#  tekartik_build_utils:
#    path: ../build_utils.dart