name: tekartik_angular2_utils
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.0.0
  tekartik_app_utils:
    git: git://github.com/tekartik/tekartik_app_utils.dart

dev_dependencies:
  browser: ^0.10.0
  test: any
  dev_test: any
  dart_to_js_script_rewriter: ^1.0.1
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points:
    - web/main.dart
    - example/side_bar/main.dart
- dart_to_js_script_rewriter
dependency_overrides:
#  tekartik_app_utils:
#    path: ../tekartik_app_utils.dart